# Generated by Django 4.2 on 2025-05-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_review_reviewlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip/Postal Code'),
        ),
    ]
