# Generated by Django 4.2 on 2025-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='transfer_slip',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_slips/'),
        ),
    ]
